name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ['3.7', '3.8']

    steps:
    - uses: actions/checkout@v2

    - name: Configure Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |
        pip install ."[all]"

    - name: Unit Tests
      run: |
        pytest --cov-report=xml

    - name: Unit Tests Coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
